---
title: "Course Schedule"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br />

<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&showTz=0&mode=AGENDA&height=600&wkst=1&bgcolor=%23ffffff&src=pqu7curfgfuf8re02dcufueuto%40group.calendar.google.com&color=%23182C57&ctz=Europe%2FStockholm" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>


```{r cals, include=FALSE, eval=FALSE}
<iframe src="https://outlook.office365.com/owa/calendar/dfb5425eac1f40c398ae5fd9697124fa@phdstudent.hhs.se/87631f6e45244713911900bc203548797012865045855732535/calendar.html" width="1100" height="700" frameborder="0" scrolling="no"></iframe>

<iframe src="https://outlook.office365.com/owa/calendar/dfb5425eac1f40c398ae5fd9697124fa@phdstudent.hhs.se/87631f6e45244713911900bc203548797012865045855732535/calendar.html"  width="1100" height="700" style="border-width:0" frameborder="0" scrolling="yes"></iframe>

```


<a href="https://calendar.google.com/calendar/ical/pqu7curfgfuf8re02dcufueuto%40group.calendar.google.com/public/basic.ics" style="color:blue;">iCal Link</a>



