---
title: "SSE Intro to R"
author: "Instructor:  Andrew Proctor"
output: 
  html_document:
    theme: flatly
    df_print: kable
    highlight: haddock
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
   
---
```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<br>

## Course Description

This is an introduction to the R statistical programming language, focusing on
essential skills needed to perform data analysis from entry, to preparation, analysis,
and finally presentation.  During the mini-course, you will not only learn basic
R functionality, but also how to leverage the extensive community-driven package 
ecosystem, as well as how to write your own functions in R.

Course content is broken up into 6 seminars, each covering one content module,
with a short additional session on Bayesian methods at the end for those 
interested. The length of each seminar may vary from module to module, but should 
generally be less than 3 hours.  The first 30-45 minutes will be used to introduce 
new information, while the remainder of the time will be spent doing hands-on 
practice.  The content for each module will be posted the day before the seminar,
so that you can familiarize yourself with the material ahead of time if you like 
(though this isn't required).

<br>

## Course Content

### **Module 1:**  Introduction to Base R Environment (Feb 1^st^ and 2^nd^)

This module introduces the R programming language and the RStudio software.  R 
programming topics will include coverage of basic operations
and data object types, especially vectors, matrices, and data frames.

- **Lecture** **Notes**:   \ \ \ \ \ 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/module1.html" role="button">Webpage</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/module1-baseR.pdf" role="button">Slides</a> 

- **Seminar Exercises:**   \ \ \ \ \   <a class="btn btn-primary" href="https://www.datacamp.com/courses/6356" role="button">DataCamp Exercises</a>


<br>


### **Module 2:**  Data Manipulation Using the Tidyverse (Feb 5^th^ and 6^th^)

This module introduces a series of tools for data manipulation/preparation 
collectively known as the "Tidyverse."  Specifically, this module covers how to 
subset data, arrange it, transform it, and aggregate it.  Participants will also 
learn convenient tools to import and export data.

- **Lecture** **Notes**:   \ \ \ \ \ 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/module2.html" role="button">Webpage</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/module2-dataprep.pdf" role="button">Slides</a> 

  
- **Seminar Exercises:**   \ \ \ \ 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/exercise-m2.pdf" role="button">Exercise</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/regions.csv" role="button">regions.csv</a>   


<br>


### **Module 3:**  Loops, Conditionals, and Joins (Feb 13^th^ and 14^th^)

This module introduces more advanced programming techniques to adapt R 
functionality to your own specific problems.  Contents include how to
perform loops, use conditional statements, and write basic functions.  In 
addition, this module will cover how to join data sets in R using 
Tidyverse functions.

- **Lecture** **Notes**:   \ \ \ \ \ 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/module3.html" role="button">Webpage</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/module3.pdf" role="button">Slides</a> 
  
- **Seminar Exercises:**   \ \ \ \ 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/exercise-m3.pdf" role="button">Exercise</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/exercise_m4_solution.R" role="button">Solutions</a> 


<br>


### **Module 4:**  Project Management and Dynamic Documents (Feb 15^th^ and 16^th^)

This module provides a few major enhancements to the workflow process of data 
analysis in R.  Fist, Knitr and RMarkdown are introduced as a means to create 
dynamic reports from R using a variety of formats, such as HTML pages, PDF 
documents, and beamer presentations.  Then, RStudio Projects are introduced as 
means of organizing folders for empirical projects.  Finally, Git and GitHub are 
introduced to perform version control.

- **Lecture** **Notes**:   \ \ \ \ \ 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/module4.html" role="button">Webpage</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/module4.pdf" role="button">Slides</a> 
  
- **Seminar Exercises:**   \ \ \ \ 
<a class="btn btn-primary" href="m4_SetupInstructions.pdf" role="button">Setup Instructions</a> 
<a class="btn btn-primary" href="https://andrewproctor.github.io/rminicourse/assets/exercise-m4.pdf" role="button">Exercise</a> 

<br>


### **Module 5:** Regression Modelling and Visualizing Data in R (Feb 22^nd^ and 23^rd^)

In this module, standard methods of regression analysis in R are presented, in 
addition to coverage of common diagnostics and post-estimation procedures.  In 
addition, the ggplot2 package is introduced as a means of creating compelling 
graphs in R.

  - Lecture Notes: 
  
  - Seminar Exercise:
  
 <br>
 

### **Module 6:**  Capstone Project (Feb 28^st^ and March 1^st^)

In this module, you will use the skills developed over the preceding seminars to
perform an analysis of an empirical problem in R from start to finish.

  - Seminar Exercise:

<br>


### **Module 7:**  Intro to Bayesian Methods in R (March 2^nd^)

This module introduces the basic intuition of Bayesian statistical methods and how
to perform Bayesian analysis in R, primarily using the rstanarm package.

  - Lecture Notes:
  
  - Seminar Exercise:
  

<br>
<br>


## Contact:

   **Course Teacher:**  Andrew Proctor
  
   **Office:**  A 711 (Arrange by email or stop in if I'm there.)
  
   **Email:**  andrew.proctor@phdstudent.hhs.se

