---
title: "Module 4 Exercise"
output: 
  pdf_document:
      highlight: haddock
urlcolor: blue

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Enable version control in RStudio

Go to **Tools - Global Options - Git/SVN** and click the "Enable version control 
for RStudio" so that version control is enabled.

### Add RStudio SSH Key to GitHub
While you are on the page, click **Create RSA Key**. You don't need to add a 
passphrase, just create the key.  When it is created, copy the key.

Then go to your GitHub account, click on your user icon in the top right of the 
screen, then click **Settings**.

From there, click **SSH and GPG Keys** and then click on **New SSH key**.  Paste 
the key into the **Key** box --- you don't need to add a title.  Click on **Add 
SSH key** to finish adding the RStudio key.

### Create a R project with remote version control

- In RStudio, then create a new project with remote version control, setting it 
up for use with your Github course repository.

- Now as make changes on the document below, use version control to routinely 
update your documents on GitHub.

### Create a PDF document with Module 3 Exercise instructions and results

- Using the Module 3 instructions and either your own code or the suggested 
solutions code to Module 3 exercises, try to create a single PDF document which 
shows:
  
    + The instructions for each task, formatted as in the PDF,
    + Your code
    + Each dataframe created (IMDB 250, Top Box Office 
    Movies, and the Combined Dataset) is displayed.

- Make sure the results have the following:

    + Code highlighting with your style of choice
    + A table of contents
    + Dataframes printed as tibbles
    
#### Create an HTML copy

Now that you have a PDF copy, try saving a new copy of your RMarkdown file that 
you will then use to generate the same document as a webpage.

- After saving the new copy, change the output type so that it is a HTML document. 

- Choose a theme for your HTML page.

- Change the chunks so that there is 
[code folding](https://rmarkdown.rstudio.com/html_document_format.html#code_folding). 
Also check out what happens if you instead set *echo* to FALSE for some chunks.

- Change the dataframe printing to Kable, looking at the dataframe after each 
step using [head()](https://www.rdocumentation.org/packages/utils/versions/3.4.3/topics/head) 
instead of displaying the data frame itself.

#### Now create a Beamer presentation copy

Once again, save another copy of your work, now for use in generating a Beamer 
presentation (you can try out other presentation types if you prefer).  You need 
only present questions 1 and 2 in the presentation.

- This time, keep [head()](https://www.rdocumentation.org/packages/utils/versions/3.4.3/topics/head) 
in the document but set the chunk options so that no output is displayed, just 
the code itself.

- Choose a Beamer Theme and Color Theme to apply to your presentation.  Check out 
the RStudio page on how to specify these options [here](https://rmarkdown.rstudio.com/beamer_presentation_format.html#themes) 
and then choose a theme and color theme from the [Theme Matrix](https://hartwork.org/beamer-theme-matrix/).

- Add an [image](http://s2.quickmeme.com/img/99/9903c7c14add3fd0758b7b5b80c24d48101f296f13ce34736799a82c71f61bc2.jpg) to the last slide of
your presentation.

